datasource:
    url: jdbc:hsqldb:mem:dataSource
    username: sa
    password:
---
spring:
  jersey.type: filter
  profiles.active: local
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/tfg?autoReconnect=true&useSSL=false&serverTimezone=UTC
    username: manuexcd
    password: contrasena
---
spring:
  profiles: container
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://mysql:3306/docker?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    username: docker
    password: docker
---
spring:
  profiles: service
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://springmysqlservice_mysqlservice:3306/docker?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    username: docker
    password: docker
---
server:
  port: 8081