version: '3.3'

services:
   mysql:
      container_name: mysql
      image: mysql
      restart: always
      environment:
         MYSQL_ROOT_PASSWORD: root
         MYSQL_DATABASE: tfg
         MYSQL_USER: docker 
         MYSQL_PASSWORD: docker
      ports:
         - 3306:3306
      networks:
         - tfg-network
      volumes:
         - mysql-volume:/var/lib/mysql
   tfg:
      container_name: tfg
      image: manuexcd/tfg
      restart: always
      environment:
         SPRING_PROFILES_ACTIVE: docker
      ports:
         - 8443:8443
      networks:
         - tfg-network
      labels: 
         kompose.service.type: loadbalancer
networks:
   tfg-network:
volumes:
   mysql-volume:
   
       
