apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: mysql
  name: mysql
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mysql
    spec:
      containers:
      - env:
        - name: MYSQL_DATABASE
          value: tfg
        - name: MYSQL_PASSWORD
          value: docker
        - name: MYSQL_ROOT_PASSWORD
          value: root
        - name: MYSQL_USER
          value: docker
        image: mysql
        name: mysql
        args:
           - "--ignore-db-dir=lost+found"
        ports:
        - containerPort: 3306
          name: mysql
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/mysql/data/data
          name: mysql-volume
      restartPolicy: Always
      volumes:
      - name: mysql-volume
        persistentVolumeClaim:
          claimName: mysql-volume
status: {}
