apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  labels:
    app: mysql
data:
  master.cnf: |
    # Apply this config only on the master.
    [mysqld]
    skip-grant-tables
    log-bin
  slave.cnf: |
    # Apply this config only on slaves.
    [mysqld]
    skip-grant-tables
    super-read-only

