version: '3'
services:
  springappservice:
   image: springapp
   environment:
       - SPRING_PROFILES_ACTIVE=service
   deploy:
     replicas: 1
   ports:
   - "8081:8080"
   networks:
    - servicenet
 
  mysqlservice:
   image: mysql
   environment:
       - MYSQL_ROOT_PASSWORD=root
       - MYSQL_DATABASE=docker
       - MYSQL_USER=docker
       - MYSQL_PASSWORD=docker
   deploy:
     replicas: 1
   ports:
   - "3306:3306"
   networks:
    - servicenet
networks:
  servicenet: